---
- name: Generate guacamole.properties file from template
  template:
    src: "{{ GUAC_CONF }}.j2"
    dest: "{{ GUAC_CONF_DIR }}{{ GUAC_CONF }}"

- name: create symbolic links
  file:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    state: link
  loop:
    - { source: '{{ LIB_DIR }}guacamole.war', destination: '/var/lib/tomcat/webapps/guacamole.war' }
    - { source: '/etc/guacamole/{{ GUAC_CONF }}', destination: '/usr/share/tomcat/.guacamole/{{ GUAC_CONF }}' }
    - { source: '{{ LIB_DIR }}lib/', destination: '/usr/share/tomcat/.guacamole/lib' }
    - { source: '{{ LIB_DIR }}extensions/', destination: '/usr/share/tomcat/.guacamole/extensions' }
#    - { source: '/usr/local/lib/freerdp/guac*', destination: '/usr/lib64/freerdp' }



