---
- name: Install pymysql
  pip:
    name: pymysql
    state: present

- name: Start and Enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: true
    
- name: Set root password for mariadb
  mysql_user:
    name: root
    host: "{{ MYSQL_HOSTNAME }}"
    password: "{{ DB_PASSWD }}"
    state: present
  ignore_errors: true   # PASSWORD ALREADY SET

- name: Delete Anonymous Users {{ MYSQL_HOSTNAME }}
  mysql_user:
    name: ""
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    host: "{{ MYSQL_HOSTNAME }}"
    state: absent

- name: Delete Anonymous Users {{ ansible_fqdn }}
  mysql_user:
    name: ""
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    host: "{{ ansible_fqdn }}"
    state: absent

- name: Remove root remote access
  mysql_user:
    name: root'
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    password: "{{ DB_PASSWD }}"
    host: "{{ item }}"
  loop:
    - "::1"
    - "127.0.0.1"
    - "localhost"

- name: Remove test database
  mysql_db:
    db: test
    login_user: root
    login_password: "{{ DB_PASSWD }}"
    state: absent

# TODO: CLEANUP - USE MYSQL MODULE
- name: Create {{ DB_NAME }} Database
  command: 'mysql -u root -p{{ DB_PASSWD }} -e "CREATE DATABASE {{ DB_NAME }};"'

- name: Grant User access to Database
  shell: 'mysql -u root -p {{ DB_PASSWD }} -e "GRANT SELECT,INSERT,UPDATE,DELETE ON {{ DB_NAME }}.* TO {{ DB_USER }}@localhost IDENTIFIED BY {{ DB_PASSWD }};"'

- name: Flush Priviledges
  command: 'mysql -u root -p {{ MYSQL_PASSWD }} -e "FLUSH PRIVILEGES;"'

- name: Create Guacamole Database
  shell: "cat extension/mysql/schema/*.sql | mysql -u root -p {{ DB_PASSWD }} -D {{ DB_NAME }}"

