---
- name: add guacd system group
  group:
    name: "{{ GUACD_USER }}"
    system: true
    state: present

- name: add guacd system user
  user:
    name: "{{ GUACD_USER }}"
    system: true
    shell: "/bin/nologin"
    group: "{{ GUACD_USER }}"
    comment: "{{ GUACD_USER }}"

- name: Edit guacd.service to use guacd system user
  lineinfile:
    path: /etc/systemd/system/guacd.service
    regexp: '^User='
    line: "User={{ GUACD_USER }}"
