---
- name: Build a Complete RH certification KVM Guacamole Virtual Lab
  hosts: kvmserver
  become: true
    
  roles:
    - role: guacamole-lab
      when: ansible_os_family == 'RedHat'
#    - role: kvm-lab
